version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "install step"
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync --delete build/ "s3://9-sister-react-app"
