version: 0.2
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync --delete . "s3://9-sister-react-app"
